SESSION_COOKIE_NAME = "pec_mock_session"

MOCK_CONFIG = {
    "id": "1",
    "smtpConfigurado": False,
    "internetHabilitada": True,
    "linkInstalacaoConfigurado": True,
    "govBREnabled": False,
    "versao": "5.4.36",
    "buscaCidadaoPorPropriedadesEnabled": False,
    "oldPecConnected": True,
    "firebaseEnabled": False,
    "ativado": True,
    "treinamento": True,
    "isPrescricaoDigitalEnabled": False,
    "rocksdbEnabled": True,
    "tipoInstalacao": "PRONTUARIO",
    "cadastroDomiciliarViaCdsEnabled": False,
    "anexoArquivosEnabled": True,
    "frontendLogLevel": "OFF",
    "__typename": "Info",
}

MOCK_FLAGS = [
    {
        "id": "36",
        "nome": "ULTIMOS_ACESSOS_ENABLED",
        "valor": True,
        "__typename": "FlagInfo",
    },
    {
        "id": "38",
        "nome": "M_CHAT_ENABLED",
        "valor": True,
        "__typename": "FlagInfo",
    },
    {
        "id": "40",
        "nome": "PROGRAMA_DIGNIDADE_MENSTRUAL_ENABLED",
        "valor": True,
        "__typename": "FlagInfo",
    },
]

MOCK_PEC_USERS = {
    "12345678901": {
        "password": "Senha1234!",
        "profissional": {
            "id": "7",
            "cpf": "12345678901",
            "cns": "898001160123456",
            "nome": "Profissional Demo",
            "nomeSocial": None,
            "conselhoClasse": {
                "id": "461",
                "sigla": "CRM",
                "descricao": "CONSELHO REGIONAL DE MEDICINA",
                "__typename": "ConselhoClasse",
            },
            "numeroConselhoClasse": "12345",
            "ufEmissoraConselhoClasse": {
                "id": "7",
                "nome": "DISTRITO FEDERAL",
                "sigla": "DF",
                "__typename": "UF",
            },
            "usuario": {
                "id": "7",
                "aceitouTermosUso": True,
                "aceitouTermoTeleinterconsulta": False,
                "forcarTrocaSenha": False,
                "visualizouNovidades": True,
                "mostrarPesquisaSatisfacao": False,
                "notificaNovidadesVersao": True,
                "hashId": "demo-user-hash",
                "__typename": "Usuario",
            },
            "acessos": [
                {
                    "id": "590",
                    "tipo": "LOTACAO",
                    "cbo": {
                        "id": "461",
                        "nome": "MEDICO DE FAMILIA E COMUNIDADE",
                        "cbo2002": "225142",
                        "actions": {
                            "cadastroDomiciliar": {
                                "enabled": True,
                                "hint": None,
                                "__typename": "Action",
                            },
                            "cadastroIndividual": {
                                "enabled": True,
                                "hint": None,
                                "__typename": "Action",
                            },
                            "atividadeColetiva": {
                                "enabled": True,
                                "hint": None,
                                "__typename": "Action",
                            },
                            "__typename": "CboActions",
                        },
                        "__typename": "Cbo",
                    },
                    "equipe": {
                        "id": "1",
                        "nome": "Equipe ESF 1",
                        "ine": "2561267370",
                        "__typename": "Equipe",
                    },
                    "unidadeSaude": {
                        "id": "1",
                        "nome": "UBS Demo Centro",
                        "cnes": "1234567",
                        "tipo": {
                            "id": "1",
                            "codigoMs": "01",
                            "__typename": "TipoUnidadeSaude",
                        },
                        "subtipo": None,
                        "tipoEstabelecimento": "UBS",
                        "isEstabelecimentoAtencaoPrimaria": True,
                        "__typename": "UnidadeSaude",
                    },
                    "__typename": "Lotacao",
                }
            ],
            "__typename": "Profissional",
        },
    }
}

MOCK_CITIZENS = [
    {
        "id": "1001",
        "cpf": "11122233344",
        "cns": "898001160000111",
        "nisPisPasep": None,
        "nome": "Maria Silva",
        "nomeSocial": None,
        "nomeTradicional": None,
        "dataNascimento": "1989-04-12",
        "dataAtualizado": "2026-05-01T10:00:00Z",
        "dataObito": None,
        "numeroDocumentoObito": None,
        "sexo": "FEMININO",
        "nomeMae": "Ana Silva",
        "nomePai": "Jose Silva",
        "telefoneResidencial": "6133334444",
        "telefoneCelular": "61999990001",
        "telefoneContato": "61988887777",
        "email": "maria.silva@example.test",
        "area": "01",
        "microArea": "001",
        "endereco": {
            "cep": "70000000",
            "uf": {"id": "7", "nome": "DISTRITO FEDERAL"},
            "municipio": {"id": "5300108", "nome": "BRASILIA"},
            "bairro": "CENTRO",
            "tipoLogradouro": {"id": "1", "nome": "RUA"},
            "logradouro": "RUA DAS FLORES",
            "numero": "100",
            "semNumero": False,
            "complemento": "CASA 2",
            "pontoReferencia": "PROXIMO A PRACA",
        },
        "localidadeExterior": None,
        "prontuario": {
            "id": "9001",
            "gestacoes": [],
            "preNatalAtivo": None,
            "puerpera": False,
        },
        "identidadeGeneroDbEnum": "CIS_FEMININO",
        "etnia": None,
        "racaCor": {"id": "1", "nome": "BRANCA", "racaCorDbEnum": "BRANCA"},
        "cbo": None,
        "escolaridade": {"id": "3", "nome": "ENSINO MEDIO COMPLETO"},
        "ativo": True,
        "localidadeNascimento": {
            "id": "5300108",
            "nome": "BRASILIA",
            "uf": {"id": "7", "sigla": "DF"},
        },
        "faleceu": False,
        "possuiAgendamento": False,
        "unificado": False,
        "unificacaoBase": False,
        "cidadaoVinculacaoEquipe": {
            "id": "2001",
            "tpCdsOrigem": "PEC",
            "utilizarCadastroIndividual": True,
            "unidadeSaude": {"id": "1", "nome": "UBS Demo Centro"},
            "equipe": {"id": "1", "nome": "Equipe ESF 1", "ine": "2561267370"},
        },
        "tipoSanguineo": "O_POSITIVO",
        "orientacaoSexualDbEnum": None,
        "estadoCivil": {"id": "2", "nome": "CASADA"},
        "paisExterior": None,
        "nacionalidade": {"id": "1", "nacionalidadeDbEnum": "BRASILEIRA"},
        "portariaNaturalizacao": None,
        "dataNaturalizacao": None,
        "paisNascimento": {"id": "76", "nome": "BRASIL"},
        "dataEntradaBrasil": None,
        "stCompartilhaProntuario": True,
        "periodoAusenciaList": [],
        "cidadaoAldeado": None,
        "isCidadaoAusente": False,
    },
    {
        "id": "1002",
        "cpf": "55566677788",
        "cns": "898001160000222",
        "nisPisPasep": None,
        "nome": "Joao Pereira",
        "nomeSocial": "Joao P.",
        "nomeTradicional": None,
        "dataNascimento": "1977-09-05",
        "dataAtualizado": "2026-04-28T15:30:00Z",
        "dataObito": None,
        "numeroDocumentoObito": None,
        "sexo": "MASCULINO",
        "nomeMae": "Clara Pereira",
        "nomePai": "Mario Pereira",
        "telefoneResidencial": None,
        "telefoneCelular": "61999990002",
        "telefoneContato": None,
        "email": "joao.pereira@example.test",
        "area": "02",
        "microArea": "004",
        "endereco": {
            "cep": "70123456",
            "uf": {"id": "7", "nome": "DISTRITO FEDERAL"},
            "municipio": {"id": "5300108", "nome": "BRASILIA"},
            "bairro": "SUL",
            "tipoLogradouro": {"id": "2", "nome": "AVENIDA"},
            "logradouro": "AVENIDA CENTRAL",
            "numero": "500",
            "semNumero": False,
            "complemento": "APTO 12",
            "pontoReferencia": "BLOCO B",
        },
        "localidadeExterior": None,
        "prontuario": {
            "id": "9002",
            "gestacoes": [],
            "preNatalAtivo": None,
            "puerpera": False,
        },
        "identidadeGeneroDbEnum": "CIS_MASCULINO",
        "etnia": None,
        "racaCor": {"id": "2", "nome": "PARDA", "racaCorDbEnum": "PARDA"},
        "cbo": None,
        "escolaridade": {"id": "4", "nome": "SUPERIOR COMPLETO"},
        "ativo": True,
        "localidadeNascimento": {
            "id": "5300108",
            "nome": "BRASILIA",
            "uf": {"id": "7", "sigla": "DF"},
        },
        "faleceu": False,
        "possuiAgendamento": True,
        "unificado": False,
        "unificacaoBase": False,
        "cidadaoVinculacaoEquipe": {
            "id": "2002",
            "tpCdsOrigem": "PEC",
            "utilizarCadastroIndividual": True,
            "unidadeSaude": {"id": "1", "nome": "UBS Demo Centro"},
            "equipe": {"id": "1", "nome": "Equipe ESF 1", "ine": "2561267370"},
        },
        "tipoSanguineo": "A_POSITIVO",
        "orientacaoSexualDbEnum": None,
        "estadoCivil": {"id": "1", "nome": "SOLTEIRO"},
        "paisExterior": None,
        "nacionalidade": {"id": "1", "nacionalidadeDbEnum": "BRASILEIRA"},
        "portariaNaturalizacao": None,
        "dataNaturalizacao": None,
        "paisNascimento": {"id": "76", "nome": "BRASIL"},
        "dataEntradaBrasil": None,
        "stCompartilhaProntuario": True,
        "periodoAusenciaList": [],
        "cidadaoAldeado": None,
        "isCidadaoAusente": False,
    },
]
